### ISSUE TITLE
Project-1 适配出现问题

### ISSUE THREAD

**Issue by Standing-Man** [fung-hwang/CS110L-2020spr#3]
![image](https://github.com/user-attachments/assets/5c71a57c-faf8-4f77-9535-2946a9ab87f0)
使用Porject-1适配之后:
在`Milestone 5: Setting breakpoints`期间加上`debug_data.print()`之后, 运行`cargo run samples/segfault`出现这个问题

**Comment by fung-hwang** [comment]
请给出详细信息以便复现问题，更欢迎pull requests

**Comment by registerGen** [comment]
这也许是 dep 更新后的 feature 吧？我也是这样

```toml
[package]
name = "deet"
version = "0.1.0"
authors = ["Ryan Eberhardt <reberhardt7@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = { version = "0.31.1", features = ["process", "ptrace", "signal"] }
libc = "0.2.180"
rustyline = "17.0.2"
gimli = "0.33.0"
object = "0.38.1"
memmap2 = "0.9.9"
addr2line = "0.26.0"
```
